apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 2

  selector:
    matchLabels:
      app: python-app

  template:
    metadata:
      labels:
        app: python-app

    spec:
      containers:
      - name: python-app

        image: asia-south1-docker.pkg.dev/project-125a5906-9774-4549-bad/imageregistry/python-app:latest

        ports:
        - containerPort: 5000
