name: python cicd to gke

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/717948519217/locations/global/workloadIdentityPools/github-pool1/providers/github-provider"
          service_account: "githubactions-sa@project-125a5906-9774-4549-bad.iam.gserviceaccount.com"
